### ISSUE TITLE
(side-note) PDFTK

### ISSUE THREAD

**Issue by JZL** [paultopia/mergepdfs#1]
Hi,

This isn't really an error but, since you were featured on [onethingwell](http://onethingwell.org/) I thought I would mention [pdftk](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/) which is cross platform and really powerful (it's one of those utilities you take for granted to merge, split, etc a pdf until you're on a friends computer and have no idea how to continue). The only tricky thing would be forcing it into alphabetical order for a lot of files as it's meant to have file names passed into it as a command line argument. But, the easiest way I've found, is to use `ls` to sort it (can even pipe to `sort` for more complicated sorts)and then pipe it through `xargs` into the command (the only part to be wary of is spaces in the filename). The other, slightly more hacky way is to use something like `ls|sort|sed 's/^/"|sed 's/$/"'|xargs` (this is based on linux core-utils, I think it's similar in mac bash) then copy that output and simply paste it into pdftk: `pdftk *copied from before with quotes so spaces don't matter* cat output collated.pdf`

Sorry for the wall of text, I really like this sort of command line/pdftk usage and have found it tremendously useful

**Comment by paultopia** [comment]
Thanks for the note!  That's definitely a good tool.  Although personally, I prefer a bit more of a simple approach, especially for the convenience of users who aren't super comfortable with shell stuff.  Might be interesting though to put together a library of aliases for one-command execution of complex tasks with pdftk...

**Comment by JZL** [comment]
Yeah. Their docs are pretty good with examples, it just leans towards manipulating a few pdfs as opposed to a folder full. I also forgot, you could simply run `pdftk *.pdf cat output collated.pdf` there's just less control on the order (I think it's alphabetical)
